version: '3.8'
services:
  devcontainer:
    image: node:20-bullseye
    network_mode: service:db
    working_dir: /app
    volumes:
      - ../:/app
    command: >
      bash -c "apt-get update &&
      apt-get install -y bash curl &&
      curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash &&
      apt-get update &&
      apt-get install -y infisical &&
      npm i &&
      infisical run -- npm test"
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}


  db:
    # container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports: 
      - "6379:6379"

volumes:
  redis-data: