version: '3.8'
services:
  devcontainer-react-native:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/node:cached
    # network_mode: service:db
    command: >
      bash -c "curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash &&
            apt-get update && apt-get install -y infisical &&
            sleep infinity"

  # db:
  #   container_name: redis
  #   image: redis/redis-stack-server:latest
  #   restart: unless-stopped
  #   volumes:
  #     - redis-data:/data
  #   ports: 
  #     - "6379:6379"

# volumes:
  # redis-data: